### ISSUE TITLE
Feature: Execute command programmatically from outside

### ISSUE THREAD

**Issue by micovi** [ndabAP/vue-command#126]
Is there any possibility to execute a command from outside? something like this.$refs.console.$_executeCommand('help'); ?

**Comment by krmax44** [comment]
Not yet! But seems like a sensible feature. As a hacky workaround for now, you could set the last input's value to your command and trigger an enter keyup event.

**Comment by ndabAP** [comment]
Closing since inactivity.

**Comment by Baloneo** [comment]
please add this feature
