### ISSUE TITLE
Bar customization using slots not working in NuxtJS

### ISSUE THREAD

**Issue by farajist** [ndabAP/vue-command#138]
I have tried to customize the bar using slots in my NuxtJS project, but the content always falls back to default (showing only title)

**Comment by krmax44** [comment]
Could you please share your code?

**Comment by farajist** [comment]
Okay this is the template of `VueCommandWrapper.vue` : 

`<template>
  <div class="term-container text-base text-left border-none mt-8">
    <vue-command
      :prompt="prompt"
      :yargs-options="{ alias: { color: ['colour'] } }"
      :commands="commands"
      show-help
    >
        <template slot="bar">
          <div class="buttons">
              <div id="red" @click.stop="switchTerm"></div>
              <div id="yellow"></div>
              <div id="green"></div>    
          </div>
          <div class="text-gray-900 self-center">
              {{ prompt }}
          </div>
          <div></div>
      </template>
    </vue-command>
    <button class="pt-4 underline m-auto" @click="switchTerm">Close fTerm</button>
  </div>
</template>`

**Comment by krmax44** [comment]
Instead of `<template slot="bar">` it should be `<template v-slot:bar>`.

**Comment by farajist** [comment]
Tried both using `<template v-slot:bar>` and `<div slot="bar"> as in the docs example but not working, you can check the my repo here :

[VueCommandWrapper.vue](https://github.com/farajist/farajist.me/blob/%2383-vue-term-strikes/components/ui/Common/VueCommandWrapper.vue)

**Comment by ndabAP** [comment]
Closing since inactivity.
