### ISSUE TITLE
Feature: Changing the terminal font via API

### ISSUE THREAD

**Issue by akkuman** [ndabAP/vue-command#162]
I wonder if it have a interface to change the terminal's font

**Comment by ndabAP** [comment]
That's a good point. Because there is no dedicated way. Users would need to search inside the library.

But I never provided an easy API for changing the font of a library. Do you know sensible approaches for that?

**Comment by akkuman** [comment]
I don't know much about the frontend.
But I think it might be possible to do this with embedded stylesheets, like :style.

**Comment by twizzler** [comment]
Hello, I would like to take care of this issue, could you explain what exactly you mean by changing the font of a library ?
And, embedded stylesheets using the style directive could indeed be a solution if you want dynamic fonts. Javascript also allows changing fonts through the style property of an element.
