### ISSUE TITLE
Bug: Spaces in options

### ISSUE THREAD

**Issue by kdlslyv** [ndabAP/vue-command#176]
Hi,

In earlier versions I could input options like this one:

`exec Do-Stuff --stuff "great stuff"`

this does not check out currently.
Having `yargs` in earlier versions did this really well.

For reproduction, use the demos `reverse` command like this:
`reverse "text with space"`

**Comment by ndabAP** [comment]
Hey @kdlslyv,

sorry for the late reply. That's very unfortunate since `getopts` promised:

> You can use it as a drop-in replacement for yargs

I'll propagate the issue to `getopts` and will see if they react. If not I'll switch back to `yargs`.

**Comment by jorgebucaran** [comment]
Hi everyone. I couldn't reproduce any issue with spaces in getopts, but [found that here](https://github.com/ndabAP/vue-command/blob/6f19260da4413a956933be0dbc5d90a9f77797c6/src/hosted/App.vue#L159), `stdin` was something like:

```console
reverse "a b c"
```

So, instead of `stdin.split(' ')[1]`:

```js
const argument = stdin.split(' ').slice(1).join(' ')
```

or 

```js
const argument = stdin.split(' ').slice(1).join(' ').replace(/"/g, '')
```

(if you also want to get rid of `"`s.)

And it seems to be working now. Hope I was able to help! 👋 

<img width="1440" alt="スクリーンショット 2020-06-12 17 28 49" src="https://user-images.githubusercontent.com/56996/84482362-8d2f0500-acd2-11ea-8731-9917d070c83c.png">

**Comment by ndabAP** [comment]
@kdlslyv please see @jorgebucaran post. Do you may have another reproduction example?

**Comment by ndabAP** [comment]
Well guys, lack of sleep and stress lead to this. I need to correct this: The `reverse` command is a built-in command and not parsed by `getopts` at all. Built-in commands can use their own parser.

**Comment by kdlslyv** [comment]
looks good; I suppose I erroneously made the same mistake. Will test tmr and close this.
Thank you for the replies & quick solution guys!

**Comment by jorgebucaran** [comment]
I just [added a new test](https://github.com/jorgebucaran/getopts/commit/71c4f3a41b3a9056793f09bbc018766a5b9696f1) to cover whitespace with long options too. Thanks! :)

**Comment by ndabAP** [comment]
Great,

**Comment by kdlslyv** [comment]
thanks for the quick resolution, working with stdin works.

however when using the `({ _ })` [see here](https://github.com/ndabAP/vue-command/blob/6f19260da4413a956933be0dbc5d90a9f77797c6/src/hosted/App.vue#L125) - the bug still applies, try `cd "te st"`
it'll list it like this in the array: `"te, st"`

**Comment by jorgebucaran** [comment]
@kdlslyv Hmm that's probably not a bug in getopts, but if you could create a minimal reproduction of the bugs with getopts, I'd have a look right away.

**Comment by kdlslyv** [comment]
@jorgebucaran thank you for your effort, but `getopts` does its job flawlessly.

the culprit is this in [handle.js](https://github.com/ndabAP/vue-command/blob/b01b2adbaba0a4717f861047ad2b606a3d7f50b0/src/mixins/handle.js#L42)

I've hacked around it using the `stdin.sync` prop and a rather hacky solution parsing how I want it, it probably is not the most fitting solution that'd apply to anyone, otherwise I'd open a pull request.

**Comment by ndabAP** [comment]
@kdlslyv I'd appreciate a PR!

**Comment by kdlslyv** [comment]
@ndabAP thanks - I'll put something worthwhile (hopefully - we'll check) together on the weekend, wouldn't want to pollute this awesome project 🙈
