### ISSUE TITLE
Bug: Up and down keys are captured by the VueCommand

### ISSUE THREAD

**Issue by WitteStier** [ndabAP/vue-command#178]
Hi,

First of all thanks for the project, it saves me a lot of time.

Next:
https://github.com/ndabAP/vue-command/blob/6f19260da4413a956933be0dbc5d90a9f77797c6/src/components/VueCommand.vue#L44-L45  

Here you add listeners for the up and down keys and prevent the default behavior. Because of this, the nano editor cannot use the up and down keys. see https://ndabap.github.io/vue-command/

Do you think its a good idea to make these event listeners optional? And if so, can you point me in the right direction so I can make a pr.

Im thinking of removing the prevent modifiers and add `event.preventDefault()` in the `increaseHistory` and `decreaseHistory` methods. So that you can disable the history when the nano editor is started. What do you think?

**Comment by ndabAP** [comment]
> Hi,
> 
> First of all thanks for the project, it saves me a lot of time.

Thanks a lot :) Curious how you use the library.

> Here you add listeners for the up and down keys and prevent the default behavior. Because of this, the nano editor cannot use the up and down keys

Very good point. Basically most of arrow key inputs are not available and that's not correct!

> Im thinking of removing the prevent modifiers and add event.preventDefault() in the increaseHistory and decreaseHistory methods. So that you can disable the history when the nano editor is started. What do you think?

Yeah, that's the way to go. Maybe like this:

```js
increaseHistory (event) {
  if (this.disableHistory || this.isInProgress) {
    return
  }

  event.preventDefault()
}
```

`isInProgress` is `true` when a command executing, which would be the case if the Nano editor has been started.

**Comment by WitteStier** [comment]
> Thanks a lot :) Curious how you use the library.

For my personal [website](https://staging.wittestier.nl/). 

> Very good point. Basically most of arrow key inputs are not available and that's not correct!

What do you mean?

**Comment by WitteStier** [comment]
It seems that this issue will be fixed by #146.

**Comment by ndabAP** [comment]
>For my personal website.

I like it! Feels super native in full screen 💪

>What do you mean?

I just meant that every application that uses my library cannot assign the arrow keys because it's overwritten bei the library. Just wanted to underline it's definitely a bug!

>It seems that this issue will be fixed by #146.

Ah no, I close it right away. I tried around but wasn't happy with the final API design.

**Comment by ndabAP** [comment]
@WitteStier does the problem still persist? If yes, I'll reopen the issue.

**Comment by WitteStier** [comment]
Hi,

Yes the problem is still there. I also found another related bug, if you open the nano editor and press Ctrl + r, the search command will be opened and closes the nano editor. So i created a PR to prevent the default events when the last command is still in progress.
