### ISSUE TITLE
Question: Idiomatic way of receiving user input without requiring 'commands'

### ISSUE THREAD

**Issue by JoshuaBThompson** [ndabAP/vue-command#207]
I wanted to do something like:
1. disable using commands so that when user enters some text vue-command does NOT try to parse for commands but just stores input in a buffer
2. when user presses 'enter' vue-command returns the text that was entered

Trying to create a python interpreter terminal using vue-command:
```bash
>> print("hello world")
>> hello world
>> x = 7
>> print(x)
>> 7
```
Is there an idiomatic way to do this with vue-command?

Thanks!

**Comment by ndabAP** [comment]
I think built-in commands are what you're looking for. I'll provide a longer anwser tomorrow.

**Comment by JoshuaBThompson** [comment]
Great! I eagerly await your response.

**Comment by ndabAP** [comment]
@JoshuaBThompson this comes close to what you want:

```vue
<template>
  <main>
    <h1><a href="https://github.com/ndabAP/vue-command">vue-command</a></h1>
    <p>A fully working, most feature-rich Vue.js terminal emulator.</p>

    <vue-command
      :built-in="builtIn"
      :commands="{}"
      :cursor.sync="cursor"
      :history.sync="history"
      :is-in-progress="isInProgress"
      prompt=">> "
      :pointer="pointer"
      :stdin.sync="stdin"
      title="">
    </vue-command>
    <pre>
      <code>
$ npm i --save vue-command
      </code>
    </pre>
  </main>
</template>

<script>
import VueCommand from '../components/VueCommand'
import { createStdout } from '../library'

const PROMPT = '~neil@moon:#/'

export default {
  components: {
    VueCommand
  },

  data: () => ({
    builtIn: undefined,
    cursor: 0,
    executed: new Set(),
    history: [],
    isInProgress: false,
    pointer: 0,
    prompt: PROMPT,
    stdin: ''
  }),

  created () {
    this.builtIn = stdin => {
      this.isInProgress = true

      // Send STDIN your Python API endpoint
      // ...

      this.executed.delete(stdin)
      this.executed.add(stdin)
      this.pointer += 1
      this.history.push(createStdout('>> hello world'))

      this.isInProgress = false
    }
  }
}
</script>
```

I'll make it more accessible. Your case showed me I need to change some things.

**Comment by JoshuaBThompson** [comment]
@ndabAP thanks!
I tried it out but maybe I need to edit the code because I'm getting some errors:
![Screen Shot 2020-08-11 at 7 48 35 AM](https://user-images.githubusercontent.com/11626839/89912235-2d0bf080-dba7-11ea-8870-17d7d62ba357.png)

**Comment by ndabAP** [comment]
Upgrade to newest version. I forgot to tell you ;)

**Comment by JoshuaBThompson** [comment]
@ndabAP I was just thinking that! thanks

**Comment by JoshuaBThompson** [comment]
@ndabAP thank you it works! 
it seems to work the way I'm expecting when I replace:
```js
this.history.push(createStdout('>> hello world'))
```
with
```js 
this.history.push(createStdout(''))
```

Another question,
Now that I can receive the user stdin on this callback (builtIn), I wanted to also add a method / property to update the stdout.
Is there an easy way to asynchronously inject text into the terminal without waiting for the user to add input?
I wanted my App.vue to be able to inject code into the terminal ....

Do I just make a method to call:
```js
this.history.push(createStdout('MY CODE HERE'))
```

**Comment by JoshuaBThompson** [comment]
@ndabAP 
I guess I wanted to add something like a stdOutput property that App.vue can update asynchronously so I can inject text into the terminal.... 
Something like:
```js
props: {
      stdOutput: String
  },
  watch: {
    // This would be called anytime the value of title changes
    stdOutput(newValue) {
      this.history.push(createStdout(newValue))
    }
  },
```

This seems to kind of work as expected... but is it the correct way?

**Comment by JoshuaBThompson** [comment]
@ndabAP this might be a better example of what I meant:
The uppercase text is injected by App.vue and can inject multiple lines....
Is this possible with the current vue-command code?
Thanks again Julian!

```python
PLEASE TYPE SOME CODE
>> x = 7
ALL DONE
PRESS Q TO QUIT
OR PRESS C TO CONTINUE
>> q
```

**Comment by ndabAP** [comment]
I guess you just have to push different `Stdout` in this case:

```
createStdout('PLEASE TYPE SOME CODE')
// ... input with `prompt: >>`
createStdout(`ALL DONE
PRESS Q TO QUIT
OR PRESS C TO CONTINUE`)
// ... input with `prompt: >>`
```

```js
props: {
      stdOutput: String
  },
watch: {
    // This would be called anytime App.vue changes some value synced with stdOutput
    stdOutput(newValue) {
      this.history.push(createStdout(newValue))
    }
},
```

This idea is great! I'll use it in future for this project.

**Comment by JoshuaBThompson** [comment]
thanks @ndabAP, I'll work with what you updated and get back to you if I encounter any issues.

**Comment by ndabAP** [comment]
You have to add `is-built-in` now as component property:

```vue
<vue-command
      :built-in="builtIn"
      :history.sync="history"
      :is-in-progress="isInProgress"
      :prompt="prompt"
      :pointer="pointer"
      hide-title
      is-built-in>
    </vue-command>
```
