### ISSUE TITLE
Question: Possible to prompt for additional input in command?

### ISSUE THREAD

**Issue by vinnybod** [ndabAP/vue-command#242]
Stripped down example:
```
vinnybod > delete thing
Are you sure you want to delete 'thing'? y/N
n # exits
y # continues to process command
```

I didn't see any examples of this, KilehParty and NanoEditor both accept input via eventHandlers, but that's just to terminate the command.

**Comment by ndabAP** [comment]
Unfortunately now. You would need to return your component, do the questions and terminate when finished. Maybe you have a good API idea for that :100:

**Comment by vinnybod** [comment]
Thanks, I'll work on a prototype and add it here. There may not be a need for new APIs

**Comment by Fabio101** [comment]
@vinnybod how did you end up going about this if you have since your last comment? I have a similar requirement :)

**Comment by vinnybod** [comment]
@Fabio101 The requirements for my project changed so I didn't end up needing this full terminal emulator. But I did prototype something using a custom template like the examples. I was gonna share that here, but I must have deleted the branch already.

**Comment by Fabio101** [comment]
Hmm, OK, ty
