### ISSUE TITLE
Add ability to print "intro text"

### ISSUE THREAD

**Issue by nfriend** [ndabAP/vue-command#29]
I would love the ability to print some intro text on the first line(s) of the terminal when the component is initialized (i.e. `Welcome to my-app!`).  

Off the top of my head, this could be implemented in two ways:

1. Accept a simple `welcome-text` binding
1. Accept a `startup-command` binding that runs one of the commands automatically on startup

Thanks so much for building this awesome library! 👍

**Comment by ndabAP** [comment]
That's a nice idea. Do you know a real world example (a real terminal to see how they do it)?

**Comment by nfriend** [comment]
Sure - most `bash` terminals automatically read a `.bashrc` file when they start up. So, for example, you could put something like this in `.bashrc`:

```bash
echo 'Welcome to my-app!'
```

Here's an example of what this looks like (in iTerm):

![Screen Shot 2019-04-13 at 10 46 15 AM](https://user-images.githubusercontent.com/1638631/56080593-6c6ed500-5dd9-11e9-9cca-b537d22a509c.png)

**Comment by ndabAP** [comment]
Your right, that's missing! I'll add that.

**Comment by nfriend** [comment]
🎉

**Comment by ndabAP** [comment]
I think a simple string, your first suggestion, was the better choice.

**Comment by alialaca** [comment]
Hi, I couldn't see the`intro` and `show-intro` props in _README.md_ and _Vue Command.vue_. Is it deprecated?
So how can I make a similar output with the current way?

**Comment by ndabAP** [comment]
It is indeed deprecated. You need to pass your own history array as prop
where the first entry would be your intro.
