### ISSUE TITLE
I try to use vue-command in my vue3+vite project but failed

### ISSUE THREAD

**Issue by flufy3d** [ndabAP/vue-command#331]
I got some error info

TypeError: external_commonjs_vue_commonjs2_vue_root_Vue_default.a is not a constructor
    at Module.fb15 (VueCommand.vue:90)
    at __webpack_require__ (bootstrap:19)
    at module.exports.106f (bootstrap:83)
    at node_modules/vue-command/dist/vue-command.common.js (bootstrap:83)
    at __require2 (chunk-RTNKGMRE.js?v=3c62c134:17)
    at dep:vue-command:1

is it possible to use this component in vue3?

**Comment by willy00** [comment]
Hi, I made a fork of this project and upgraded it to Vue 3, But it's still rather buggy, but it works. You can check if out [here](https://github.com/willy00/vue-command)

**Comment by tzfun** [comment]
Recommend my project to you, it works fine in Vue3.

Github: [https://github.com/tzfun/vue-web-terminal](https://github.com/tzfun/vue-web-terminal)
Demo: [https://tzfun.github.io/vue-web-terminal/](https://tzfun.github.io/vue-web-terminal/)

**Comment by ndabAP** [comment]
@flufy3d I'm working right now on a Vue.js 3 upgrade. It will be finished before this years ends. You can keep an eye on the PR: https://github.com/ndabAP/vue-command/pull/397

@c0dn impressive work!

**Comment by ndabAP** [comment]
A new version has been release. Please try it again @flufy3d.
