### ISSUE TITLE
After clear command, the in/output break

### ISSUE THREAD

**Issue by labsrelay** [ndabAP/vue-command#410]
Hi,
Could you please advise how to better handle the clear command?
bassically I do the following:
help, clear, help,  terminal stop responding, the prompt is gone, no posibility to type.

in demo it works perfect, perhaps you could share an example on Vue3.

Thanks
![clear-cmd](https://user-images.githubusercontent.com/108028720/210581825-ecf4aec8-0c4a-4464-9800-d61576d59d21.png)

**Comment by ndabAP** [comment]
Did you try it like in the examples, see https://github.com/ndabAP/vue-command/blob/main/src/hosted/App.vue#L109-L112? Do you use the newest version?

**Comment by ndabAP** [comment]
I think I found the solution:

```js
clear: () => {
  history.value = []
  query.value = ''
  return createQuery()
},
```

You must set the query to empty again. Internally, the query is still `clear`.

**Comment by ndabAP** [comment]
I'll add a mechanism that, if the history has been emptied, the terminal resets some of its value, including the query.

**Comment by labsrelay** [comment]
Many thanks for your support.
Finally, I think the issue came from using vue3-ts, when I switched to a vue3-js setup, there was no issue.

**Comment by ndabAP** [comment]
I learned in a hard lesson that you should never assign Vue.js `ref` to an empty array or object because its loosing its reactivity. This is the real solution for `clear`:

```
clear: () => {
        // "splice" is necessary since Vue.js losses its reactivity if array is
        // set to empty
        history.value.splice(0, history.value.length)
        return createQuery()
}
```
