### ISSUE TITLE
How to manually trigger command execution?

### ISSUE THREAD

**Issue by kilasuelika** [ndabAP/vue-command#459]
Consider a scene that when click a button outside `vue-command`, send a button to the terminal then print a query component and a result component. I tried to use exposed `dispatch` by:
```
import VueCommand from 'vue-command';

//......


const childRef = ref();
bus.on("exec_terminal_command", function (data) {
    childRef.value.dispatch(data);
});
```
Here `bus` is `mitt`. The error is `cannot read properties of undefined (reading 'dispatch')`.

------------
After some tests, it seems like that I can't use inject in `script setup` block:
```
import {inject} from 'vue';
import VueCommand, {
    createStdout,
    createQuery,
    newDefaultHistory,
} from "vue-command";

const setQuery=inject("setQuery");
```
giving error:
```
injection "setQuery" not found. 
```

**Comment by ndabAP** [comment]
```vue
<vue-command
    ref="vueCommand"
/>
```

```js
setup() {
  const vueCommand = ref(null)

  onMounted(() => {
    vueCommand.value.dispatch('')
  })

  return {
    vueCommand
  }
},
```

`setQuery` just sets the query and doesn't dispatch it.
