### ISSUE TITLE
Feature: Send multiple events

### ISSUE THREAD

**Issue by MaxBill** [ndabAP/vue-command#46]
Ask me how to get the input command after I return, and then I need to use it to make network requests.

**Comment by ndabAP** [comment]
That's not possible at the moment. I could send an event with the command after your program exited. What do you think?

**Comment by MaxBill** [comment]
Can you do all kinds of listening events to the terminal, such as on ('key') or get commands?

I don't know the principle of your design. I just put forward this idea.

**Comment by ndabAP** [comment]
Yeah, that would be the idea. That would make it more transparent for the user. I'd send the following events:

- While entering a command (includes the current command)
- When your program started (includes the whole command) 
- When your program exited (includes the whole command)

Is that what you need?

**Comment by MaxBill** [comment]
Thank you very much for your help and look forward to it getting better and better.

**Comment by ndabAP** [comment]
I reopen the issue as a reminder for me 🙂

**Comment by ndabAP** [comment]
@MaxBill check:

https://github.com/ndabAP/vue-command#events
