### ISSUE TITLE
Add logic signal by Ctrl+C 

### ISSUE THREAD

**Issue by starlight93** [ndabAP/vue-command#499]
Thanks for creating this library.
Can I inject some logic to listen Ctrl+C? I need to separate Ctrl+C event listener which is listened by this terminal vs just copying text from another textarea html tag. Currently I don't want to "always" focus to terminal when I do Ctrl+C.

**Comment by ndabAP** [comment]
Hey and thanks! You mean with a PR? What change do you have in your mind?
