### ISSUE TITLE
Feature: Allow commands to return components

### ISSUE THREAD

**Issue by ndabAP** [ndabAP/vue-command#5]
To imitate interactivity, like:

https://askubuntu.com/questions/1705/how-can-i-create-a-select-menu-in-a-shell-script

Returning a component as STDOUT would be appropriate. **Problem**: It may not be simple anymore to return just a string, which makes the API much more complex.

**Comment by krmax44** [comment]
I much prefer this over #36 as it's more flexible and easier. What about providing the given component with helper functions that could be accessed in lifecycle hooks? Here's an API proposal:

```vue
<template>
  <div>Loading {{ loading }}%</div>
</template>

<script>
export default {
  data() {
    return { loading: 0 };
  },
  mounted() {
    const load = () => setTimeout(() => {
      this.loading++;
      if (this.loading < 100) {
        load();
      }
      else {
        // given by vue-command, marks the process as done and allows the user to enter a new command
        this.$command.done();
      }
    }, 4);

    load();
  }
}
```

A couple of things would be nice to have here:

- Helper functions like `this.$command.done()`
- Helper components like `<vue-command-input>` (a simple input field)

> **Problem:** It may not be simple anymore to return just a string, which makes the API much more complex.

What about allowing both strings and components? A string would then be wrapped in a basic component, similar to how it is currently done.

Proposal: let's rename this to `Feature: allow commands to return Vue components`.

**Comment by ndabAP** [comment]
>Proposal: let's rename this to Feature: allow commands to return Vue components.

Makes totally sense since it may lead to other positive changes.
