### ISSUE TITLE
Feature: Clear screen method

### ISSUE THREAD

**Issue by ngyewch** [ndabAP/vue-command#61]
Is there any way to clear the screen at the moment? If not, it would make a nice enhancement.

**Comment by ndabAP** [comment]
Strange that nobody else requested this. You are totally right. Unfortunately, it's not possible at the moment. 

You could provide a pull request if you want it fast. The only problem I see here is that when you delete the [history](https://github.com/ndabAP/vue-command/blob/master/src/VueCommand.vue#L171), <kbd>↑</kbd>/<kbd>↓</kbd> wont work anymore the deleted commands.

**Comment by ndabAP** [comment]
Another thing that has to be discussed is that there are no default commands at all. It's totally to the user. But maybe the user could get access to the history.

**Comment by ndabAP** [comment]
It's not possible to provide property `built-in`, which works same as `commands` except the second argument is `$data` from the instance.

Example:

```vue
<script>
import VueCommand from './VueCommand'

export default {
  components: {
    VueCommand
  },

  data: () => ({
    commands: {
      pokedex: ({ color, _ }) => {
        if (color && _[1] === 'pikachu') {
          return 'yellow'
        }

        // Return help since no match
        return `Usage: pokedex pokemon [option]<br><br>

          Example: pokedex pikachu --color
        `
      },

      help: () => (`Usage: pokedex pokemon [option]<br><br>

        Example: pokedex pikachu --color
      `)
    },

    builtIn: {
      // Next tick is not available inside data
      reset: ({ _ }, data) => null
    }
  }),

  created () {
    this.builtIn.reset = async ({ _ }, data) => {
      data.history = []
      data.last = ''

      await this.$nextTick()

      data.history.push('')
    }
  }
}
</script>
```

**Comment by wenfangdu** [comment]
Just an aside, the document demo has this feature now.
